### ISSUE TITLE
Error in Plugin Function

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1081]
I  have created a function and it has been created through an API Call. But when I try to use it in SQL below error comes. Please provide some hints to resolve @ngjaying 

Update rule error: Parse SQL SELECT inFunction(),name FROM test error: error getting function inFunction: cannot open /kuiper/plugins/functions/inFunction.so: plugin.Open("/kuiper/plugins/functions/inFunction.so"): Error relocating /kuiper/plugins/functions/inFunction.so: __fprintf_chk: symbol not found.

**Comment by ngjaying** [comment]
@sujith1994 There are a lot of limitations for golang plugin system. Did you build and run eKuiper and the plugin in the same env? Are you using alpine version? 
I assume you have read the [plugin tutorial](https://github.com/lf-edge/ekuiper/blob/1.2.0/docs/en_US/plugins/plugins_tutorial.md). If not, please follow the build and deployment process there.

**Comment by sujith1994** [comment]
@ngjaying I had build eKuiper(1.4.0-beta) and I made the .so file successfully. That function works fine with locally build ekuiper. The same .so file I had used API Plugin Create a call to create it in 1.3.1-alpine docker.
So now different versions cause issues here right ?, if I use 1.3.1 on both sides (docker and local git clone ), it will work?

**Comment by ngjaying** [comment]
Different versions will always fail. And it is just one of the very strict requirements of golang plugin system, many aspects in the env like go version, the go path, the os etc. may fail the plugin runtime. To use native plugin, it will be safer to build the plugin and eKuiper in the exact same env such as the suggested way with docker in the tutorial.

Since you are using 1.4.0-beta, you can also try the [portable plugin](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/extension/portable/overview.md) which is much easier regarding build/deployment.

**Comment by sujith1994** [comment]
@ngjaying Thanking you for the help. i have used docker for 1.4.0-beta.1 and there i could able to build and deploy my functions.
