### ISSUE TITLE
About kuiper plugins install

### ISSUE THREAD

**Issue by wttt-py** [lf-edge/ekuiper#1135]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
For example, I want data sink it to tdengine, But too little information on the official website. it's very difficult to install td plug-in. I hope the official can have more detailed documents.
![kp1](https://user-images.githubusercontent.com/83765757/147537250-4ef56839-4421-4732-8ba3-153d9fb4d4e2.png)
![kp2](https://user-images.githubusercontent.com/83765757/147537262-3c6a0fe8-3d5b-42fb-ad85-9e5d4e118c89.png)
![kp3](https://user-images.githubusercontent.com/83765757/147537264-4498cb06-8eb6-4a3b-91ef-4d8e6876c0c4.png)

**Comment by SuperRxan** [comment]
![image](https://user-images.githubusercontent.com/33817352/147652204-f09dd03c-c503-486b-8049-128b4c3a9200.png)

you need specify the tdengine server version. in this example 2.3.1.0

I strongly suggest you upgrade the kuiper to 1.4.0 or 1.4.1(later release) and try again because tdengine plugin code are using v2 go sdk https://github.com/taosdata/driver-go.

**Comment by wttt-py** [comment]
Thanks, submited success when add the parameters;
when will have 1.4.1, I installed it 1.4.0 with the rpm package, can I update it directly without uninstalling it?

**Comment by ngjaying** [comment]
Discuss offline and get the problem resolved. It is caused by tdengine client version that is not exist. Close now.
