### ISSUE TITLE
kafka sink take more than one second to send out message

### ISSUE THREAD

**Issue by superrxan** [lf-edge/ekuiper#1778]
**Environment**:  debian

- eKuiper version (e.g. `1.3.0`):   lfedge/ekuiper:1.10.0-alpha.0   
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): linux
- Others:

**What happened and what you expected to happen**:

What happened:
kafka sink take more than one second to send out message
Another minor problem, when delivering message fails, if the error is recoverable, we should return error message starts with IOError, so that the sink cache can take effect. Check #1767 as an example.

What you expected to happen:
kafka sink should take less than 100 ms to send out message

**How to reproduce it (as minimally and precisely as possible)**:
use kafka sink to send data into kafka broker
check the metrics for rule

![image](https://user-images.githubusercontent.com/33817352/231989377-1bd2ccf0-87b0-47e0-891c-992449d72049.png)

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
@carlclone Do you have any ideas about this problem? Is it related to server or client configuration?

**Comment by carlclone** [comment]
if the topic does not exist , it might be slow at the first time due to topic creation and partition info retrieve
another possibility is the RequiredAcks param , now is set to wait all ack . 

//  RequireNone (0)  fire-and-forget, do not wait for acknowledgements from the
//  RequireOne  (1)  wait for the leader to acknowledge the writes
//  RequireAll  (-1) wait for the full ISR to acknowledge the writes

 i will give it a test .

**Comment by carlclone** [comment]
the problem comes from the kafka-go package , by default it wait for 1 second batch for sending batch message
https://github.com/segmentio/kafka-go/issues/326

setting this config can solve the problem:
 BatchTimeout:           1 * time.Nanosecond,

=== RUN   TestKafkaSink
time consuming 21 ms
time consuming 9 ms
time consuming 4 ms
--- PASS: TestKafkaSink (0.04s)

**Comment by ngjaying** [comment]
This makes sense, thank you.
