### ISSUE TITLE
Rule pipeline support

### ISSUE THREAD

**Issue by jinfahua** [lf-edge/ekuiper#506]
Darryl from Slack
--------

What is the recommended way of having a pipeline of "functions" using Kuiper?  For example, say I want the data from one type of device, say a temperature sensor to:
If the temperature is between 60F and 90F, I want to skip these values
Go through a formula (e.g. calculation of temp + 1)
Average over a window
This pipeline of 3 functions may change over time.  The kuiper way seems to be to create a single SQL statement rule of all of these for this one pipeline.  However, this can become unwieldy as the number of functions grow.  Another way is to create distinct rules, one to filter the values between 60 and 90, one for the +1 formula, and one for the average.  This is more flexible, however, the challenge then is how to pass the values from the first rule to the second to the third and also how to define which is first, second, third, etc..  This flexibility is what I really want.  How do you suggest this be done in kuiper today?  Is there anything in the roadmap to make this easier?

**Comment by jinfahua** [comment]
Currently Kuiper does not have embedded support the pipeline rule… So one possible workaround would be leveraging a third party message brokers (such as EMQ X Broker). The workflow would be as following,
source(rule1) -> pub to topic /rule1/result (rule1)--> source (rule2) -> pub to rule2/result (rule2)--> source (rule3) -> pub to rule3/result (rule3).
The basic idea of the solution is that the next rule will consume the result of previous rule. The disadvantage of this solution is depending on other 3rd party message broker.
We are planning to add embedded support for pipeline rules. For example, use the zeromq for sharing data between rules.

**Comment by dmocek** [comment]
When you implement a pipeline rule, please take into consideration the definition of the pipeline itself.  You want to be flexible enough for data to take different routes.  It would be best if you could send the pipeline route (e.g. rule1 -> rule3 -> rule2) along with the data.  The router could then automatically send the data from the results of one rule to the next in the pipeline (e.g. rule1 to rule3, then to rule2).  Using a broker like listed above would be difficult to create and maintain.  As an example, I might want to define the pipeline for a temperature sensor to look like this: rule1 -> rule3 -> rule2, and the pipeline for a humidity sensor to look like this: rule4 -> rule2 -> rule1.  Whatever system is implemented, it should be flexible enough to define discrete rules and flexible pipelines.

**Comment by ngjaying** [comment]
A normal rule has a source, one or more sinks and the sql. When putting rules into a pipeline, the rule source and sink must be modified to link with the successive rules in the pipeline. Which means, the internal "rules" are not normal rules, they are restricted. By the different definition of internal "rules", we can have different pipeline implementation. I can think of 4 pipeline design for a pipeline rule1 -> rule2 -> rule3:

1. Normal rules and virtual pipeline. This is the proposal at [comment 1](https://github.com/emqx/kuiper/issues/506#issuecomment-692496263). The rules are connected by mq(mqtt or others) topic explicitly defined. The user has to **define the 3 rules just like normal rules** with the flow source(rule1) -> pub to topic /rule1/result (rule1)--> source (rule2) -> pub to rule2/result (rule2)--> source (rule3) -> pub to rule3/result (rule3).  A virual pipeline is formed implicitly. 

   - Implementation: already supported by 3rd party mq(such as mqtt) source and sink. To eliminate the need of 3rd party mq, we can add support for an internal mq source/sink.
   - Advantage: flexible. All the rules except the first and the last rules can be linked with their mq topics
   - Disadvantage: complex to write
2. Pipeline rule with multiple SQLs instead of internal rules. The user can specify a rule to have multiple SQLs which will be executed sequentially like a pipeline. A pipeline rule json looks like below
    ```json
   {
      "sqls" : [
          "select temp from device where temp > 60 and temp < 90",
          "select temp + 1 as newtemp",
          "select avg(newtemp) group by tumblingWindow(10)
      ],
      "action":[{"log":{}}]
   }
    ```
   - Implementation: modify rule sql from string to an string array.
   - Advantage: easy to write complex behavior; better performance by running as a single rule
   - Disadvantage: Inflexible. No internal rule concept. The internal SQL can not be shared.

3. Pipeline will instantiate a new instance of internal rules with modified source and/or sink. We will have a new artifact pipeline. The definition will be like `create pipeline pipeline1 {"rules": ["rule1", "rule2", "rule3"]}`. The internal rules are normal rules with source/sinks. Each rules must be created as a normal rule. They can have freely combination in different pipelines. The rule itself can be running independently without a pipeline.
    - Implementation: add a new type `pipeline`. During pipeline initialization, the internal rules will be changed implicitly including replace source receive previous rule's result and add a sink to the successive rule. Notice that, the rule is actually instantiated with different source/sink then the single running rule itself. Only the rule definition is read and reused to instantiate it. The data flow are isolated of each rule instances. No matter the rule is running singularly or in pipeline 1 or pipeline2.
    - Advantage: very flexible. 
    - Disadvantage: implicit change of internal rules' source and/or sink, may be confusing

4. Pipeline rule with named rule template(SQL). This is a variant of idea 2. Instead of sqls, we allow to specify named sqls so that they can be reused.
 
    ```json
   {
      "sqls" : [
          "rule1",
          "rule2",
          "rule3"
      ],
      "action":[{"log":{}}]
   }
    ```
   - Implementation: modify rule sql from string to an string array; add a new artifact "ruleTemplate" (TBD), this artifact can be used at multiple pipeline rules. 
   - Advantage: somehow reflexible to reuse sql definition; better performance by running as a single rule;
   - Disadvantage: complex to manage "ruleTemplate" and may be confusing to compare with normal rule.

@dmocek Could you please check which is more close to the requirement.

**Comment by dmocek** [comment]
Hi @ngjaying This issue was on the back-burner for us for a while and it is now on the front-burner again.  How can it be re-opened?

When I originally wrote this, I thought rule reuse and flexibility was a high priority, but now I'm re-thinking it.  I now question how much sense it makes to make rules reusable for the added complexity as well as the fact that the rules are specific to the data in the stream (e.g. the #2 example above can only be used with sources that have a temp).  Questions to consider are: Is it that difficult to create rules that we need to reuse them?  How much can rules really be reused?  Without reuse, is the same rule going to be re-created that many times that it warrants the additional complexity to save the re-creation?  Considering these questions, I think you're #2 option looks the best.  This is assuming there is no functionality lost for each rule with this implementation (in other words, I can take any rule and make it part of a pipeline.

Our use is that our pipelines are applied per type of device by default (e.g. all temperature sensors) with the ability to be applied on additional filters based on meta-data (e.g. all temperature sensors in a specific location, or with a specific model number, or device name, or and all three of these).

**Comment by ngjaying** [comment]
@dmocek We implement the [rule pipeline](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/rule_pipeline.md) in 1.4.0 by preserving all "sub-rules" as normal standalone rules and chain them implicitly with the memory sink/source pair implicitly. This is very flexible and it seems meet your requirment. Please check the link and evaluate. Thanks.
