### ISSUE TITLE
Too many open files error when creating more than 1000 rules

### ISSUE THREAD

**Issue by jinfahua** [lf-edge/ekuiper#842]
[An issue](https://edgexfoundry.slack.com/archives/CE4KJ5VV2/p1623911540069700) report from EdgeX community.

I'm trying to test the performance of Kuiper, and for that I'm creating a 1000 rules,
While creating rules, I get following error in response to API call,
`Create rule error: unable to open database file: too many open files`
I'm using Kuiper 1.1.1.

**Comment by salmanazmat666** [comment]
This issue occurs for less number of rules as well. For example, I have seen this issue for 337 rules.

**Comment by rwadowski** [comment]
Hi,
I have been watching into this a little bit - I have impression that it may be related to the nature of sqlite database which serves as a store for rules. I see that `rulesHandler` method from `rest.go` depends on two operations that require db connection
* `ruleProcessor.ExecCreate`
* `createRuleState
At some level they invoke `Open` implementation of the store which which opens sql connection - which according to documentation should be invoked once, in this case it is invoked many times and results are constantly overwritten.
Shouldn't store `Open` and `Close` methods be called on startup and end of the whole application and store should manage its state on his own ?

**Comment by ngjaying** [comment]
@rwadowski I agree with you and we do need a refactor for the rule meta storage. Before moving to sqlite, the storage implementation is file kv like go-cache. The store interface is an abstraction of those kv which close after each write. When moving to sqlite, we try to keep the interface and let sqlite adapt to that which makes it not suitable to work with high throughput. The refactor is in the plan backlog. If you are interested, welcome to submit a PR. Thanks.

**Comment by rwadowski** [comment]
@ngjaying hi, I can take this one. Is there any description of contribution (branch name convention etc) ?

**Comment by ngjaying** [comment]
> @ngjaying hi, I can take this one. Is there any description of contribution (branch name convention etc) ?

Awesome! Just create a PR against master branch. Here is the [contribution doc](https://github.com/lf-edge/ekuiper/blob/master/docs/CONTRIBUTING.md).

**Comment by rwadowski** [comment]
@ngjaying how can I commit changes, I have signed off my commit and I want to push the branch and create PR then. It requires me to login into the account in the github domain. How I am supposed to do a PR ?

**Comment by ngjaying** [comment]
@rwadowski Did you create a fork? If not, you should [create one](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/about-forks) then [create the PR from it](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by rwadowski** [comment]
@ngjaying Yeah, I figured it out, done and ready.
What's more I noticed that there is similar code in the internal/topo/state/kv_store.go:50 which should be refactored. Generally maybe it would be better to use a key value store to keep such values like redis ?. Accessing one sqlite file from many placec can be problematic.

**Comment by ngjaying** [comment]
Greate work @rwadowski . We do think of using redis. We would like to provide an option/conf to let users switch the KV implementation. It seems eKuiper cannot bundle redis into the binary like sqlite, so they may be used in different scenarios.

**Comment by rwadowski** [comment]
@ngjaying As follow up on points I mentioned, shall I create issues for them ? I think I can complete sqlite refactoring in topo.go and related files to make changes applied here complementary ?

**Comment by ngjaying** [comment]
> @ngjaying As follow up on points I mentioned, shall I create issues for them ? I think I can complete sqlite refactoring in topo.go and related files to make changes applied here complementary ?

Sorry, I forgot to respond to your points about the store in topo.go. Currently, this store is actually using in different scenario. I will use topo kv to refer to the KV store in topo.go and normal kv to refer to the normal kv store.
1. Topo kv will save states data while the normal kv saves the meta data of the system.
2. Topo kv in topo is append only.
3. Topo kv is optional while the normal kv is mandatory so that we can initialize it in server startup.

Based on these comaprisons, the current implementation is like:
1. Topo kv uses a seperate sqlite data file tskv.db to isolate from normal kv as it will be written much more frequently.
2. Topo kv uses a new tskv interface (internal/pkg/tskv) to adapt to the append only feature.
3. Topo kv sqlite database connection is initialized once when the first instance is created.

In my opinion, the topo kv already has "make one place for initialization sqlite". Thus, such kind of refactoring may not be needed. 

Surely, we welcome any optimizations needed that you may find. Thanks again.

**Comment by rwadowski** [comment]
@ngjaying well I am pointing more about sqlite itself - topo has different logic and does not use this mechanic. All I wanted to do is to refactor topo to use mechanics that were implemented here (sqliteDatabase struct, mutex) and so on to avoid problems with other sqlite db. It is not about optimization but to work with sql in the same manner. Will `tskv` package will be safe from problems were here ? If yes we don't have to modify it indeed.

**Comment by ngjaying** [comment]
@rwadowski  Yes, tskv is safe from the problems. At the same time I also agree with you that they do have room to refactor and unify kv and tskv regarding the sqliteDatabase struct. But in the refactored kvStore, we now only have one Database instance, which violates the current design of tskv to use a separate sqlite file to isolate from the meta data. This may be fine when we are using redis as the storage to have one single connection. Right now, with sqlite, we prefer totally two database connections, one for meta which you have refactored and the other for topo which was a single connection now. So I agree we can abstract a database layer so that we can easily switch storage support from sqlite to redis as an example. I prefer to refactor that when we adding redis as an alternative storage implementation.

**Comment by rwadowski** [comment]
@ngjaying fair enough, I implicitly assumed that we would potentially refactor these changes to have two separated DBs but for the longer term if redis is about to be introduced these changes are not so urgent and it can wait
