### ISSUE TITLE
Use EdgeX Redis sink,  cannot find the result

### ISSUE THREAD

**Issue by jinfahua** [lf-edge/ekuiper#947]
From Community: 

> I’m using Redis for my Kuiper sink in EdgeX.  I can see that kuiper is processing my rule and sending the result to Redis, but I cannot find the data in Redis after kuiper has processed it.  Can you explain how I can find my data?  Or is there documentation somewhere?  I cannot find it anywhere.

**Comment by jinfahua** [comment]
The EdgeX sink is using Redis stream, which is possibly different from Redis K/V store. @ngjaying Jiyong will try to reproduce the problem, and see if it could be resolved by EdgeX team.

**Comment by dmocek-o** [comment]
It would be helpful to have documentation on what's going on.  Where does Kuiper send the data in Redis?  EdgeX uses keys, does Kuiper use keys or something else?  What is the name of the object used?  If it's a stream, is the stream name specified by the topic in the rule or something else?

**Comment by ngjaying** [comment]
This is more like an EdgeX problem. eKuiper EdgeX sink works like a EdgeX device that push processed messages to the EdgeX message bus and we don't care about the message bus type is redis (the default in the current EdgeX version), zeromq or mqtt. We expect the users can consume the data that published by eKuiepr edgeX sink as the same as data from other devices.

**Comment by ngjaying** [comment]
@dmocek-o Currently, eKuiper edgeX sink send the message to EdgeX message bus as the same as [application service](https://docs.edgexfoundry.org/2.0/microservices/application/Triggers/#messagebus-connection-configuration). Also as the same as app service, the published data can be received by subscribing to the topic specified and they are not sending to the core data service. The default eKuiper edgex source is actually a client of such kind of app service `app-service-rules` in the default edgex docker compose.  Check the [eKuiper edgeX source tutorial](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/edgex/edgex_source_tutorial.md）for detail.  eKuiper edgeX sink can be an alternative of app service. 

```json
{
  "id": "ruleEdgexSink",
  "sql": "SELECT * From demo",
  "actions": [
    {
      "edgex": {
        "type": "redis",
        "protocol": "redis",
        "host": "edgex-redis",
        "port": 6379,
        "topic": "ekuiperResult",
        "deviceName": "ekuiper",
        "profileName": "ekuiper",
        "sourceName": "ekuiper",
        "contentType": "application/json"
      }
    }
  ]
}
```
You can set the source topic to "edgex-redis" in eKuiper EdgeX source to consume the result from EdgeX sink or any other scenario that the app service may be used.

If you do need to get those data in core data, I guess we will need to send the data to the message bus as the same as device service aka. eKuiper as a virtual service. It is actually supported by setting the topic to `edgex/events/device/ekuiper/ekuiper/ekuiper`. There is some problem here as the data type we currently sent out is an `dtos.Event` (app service data type) rather than the `request` (device and core data data type). We would need to add this support and add more docuements.

**Comment by dmocek-o** [comment]
I am able to get the data from EdgeX when using redis as a source and sink.  I used the default docker-compose from EdgeX.  Here is my rule:

curl -X POST \
         http://$kuiper_docker:$kuiper_port/rules \
         -H 'Content-Type: application/json' \
         -d '{
         "id": "tempHumidity-rule",
         "sql": "SELECT meta(*) AS edgex_meta, temperature, humidity FROM demo WHERE (temperature >= 60 AND temperature <= 80) OR (humidity >= 60 AND humidity <= 80)",
         "actions": [
             {
                 "log":{},
                 "edgex": {
                     "contentType": "application/json",
                     "host": "edgex-redis",
                     "messageType": "request",
                     "port": 6379,
                     "protocol": "redis",
                     "topic": "ekuiper-events",
                     "type": "redis"
                 }
             }
         ]
         }'

topic refers to the Redis PubSub channel Kuiper will send data to.
